# Generated by Django 5.1.4 on 2026-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('clinic', models.CharField(blank=True, max_length=200, verbose_name='병원/소속')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='연락처')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='관심 제품')),
                ('preorder', models.BooleanField(default=False, verbose_name='사전예약 알림 동의')),
                ('note', models.TextField(blank=True, verbose_name='메모')),
                ('source', models.CharField(default='web', max_length=60, verbose_name='유입경로')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '리드(원장 회원)',
                'verbose_name_plural': '리드(원장 회원)',
                'ordering': ['-created_at'],
            },
        ),
    ]
