# Generated by Django 5.1.4 on 2026-06-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='action', max_length=60, verbose_name='보드')),
                ('key', models.CharField(max_length=120, verbose_name='키')),
                ('value', models.TextField(blank=True, verbose_name='값')),
                ('updated_by', models.CharField(blank=True, max_length=60, verbose_name='수정자')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정시각')),
            ],
            options={
                'verbose_name': '보드 셀',
                'verbose_name_plural': '보드 셀',
                'ordering': ['board', 'key'],
                'unique_together': {('board', 'key')},
            },
        ),
        migrations.CreateModel(
            name='BoardPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='action', max_length=60, verbose_name='보드')),
                ('name', models.CharField(max_length=60, verbose_name='이름')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='최근접속')),
            ],
            options={
                'verbose_name': '보드 접속현황',
                'verbose_name_plural': '보드 접속현황',
                'unique_together': {('board', 'name')},
            },
        ),
    ]
